### ISSUE TITLE
What's the difference between this project and occ

### ISSUE THREAD

**Issue by happydpc** [ricosjp/truck#7]
I am watching this project. It's very good that this's implemented in rust. And I wonder what's the major difference between this and opencascade, is there any better design inside this project?

**Comment by ytanimura** [comment]
The most significant difference lies in the small-scale crating. Overall, it is a competitor to OCCT, but the truck-platform by itself, for example, is aimed at replacing three.js in the WebGPU generation, or a primitive Unity that uses crates.io as an asset store. This design allows experts to replace individual implementations.. Moreover, it can easily accommodate to algorithm alternatives such as GPU accelerators for NURBS meshing, or unpredictable expansion for unknown new technologies. This is possible because of centralized package management by Cargo.

**Comment by happydpc** [comment]
Is there any plan to support boolean operations? Glad to implement these.

**Comment by ytanimura** [comment]
Yeah, we also consider that boolean operations are necessary and is the next plan after STEP handling.
We cannot make any official promises about deadlines, however, I'm hoping to release something by August.

**Comment by g-rauhoeft** [comment]
Another very important difference is that this project is Apache 2.0 licensed, while OCC is LGPL 2.1.

**Comment by ytanimura** [comment]
Close this issue. Boolean operations will be discussed in #17 .
